// <auto-generated />
using System;
using GAP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GAP.Migrations
{
    [DbContext(typeof(GAPContext))]
    partial class GAPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GAP.Models.DemandeAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<int?>("RespServiceAchatUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RespServiceAchatUserID");

                    b.ToTable("DemandeAchat");
                });

            modelBuilder.Entity("GAP.Models.Devis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReception")
                        .HasColumnType("datetime2");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<int>("NombrePiece")
                        .HasColumnType("int");

                    b.Property<double>("PrixTTL")
                        .HasColumnType("float");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("RespServiceAchatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("ProduitId");

                    b.HasIndex("RespServiceAchatId");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("GAP.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FournisseurEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("RespServiceFinanceId")
                        .HasColumnType("int");

                    b.Property<bool>("Validite")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("RespServiceFinanceId");

                    b.ToTable("Facture");
                });

            modelBuilder.Entity("GAP.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Nom")
                        .HasColumnType("int");

                    b.Property<int>("NombreTransaction")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseur");
                });

            modelBuilder.Entity("GAP.Models.OffreVente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<double>("PrixTTL")
                        .HasColumnType("float");

                    b.Property<bool>("Validite")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("OffreVente");
                });

            modelBuilder.Entity("GAP.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OffreVenteId")
                        .HasColumnType("int");

                    b.Property<int>("PrixTotal")
                        .HasColumnType("int");

                    b.Property<int>("PrixUnitaire")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OffreVenteId");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("GAP.Models.RapportReception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceptServiceAchatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptServiceAchatId");

                    b.ToTable("RapportReception");
                });

            modelBuilder.Entity("GAP.Models.RapportTestQualite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RespServiceQualiteId")
                        .HasColumnType("int");

                    b.Property<bool>("ValiditeEtat")
                        .HasColumnType("bit");

                    b.Property<bool>("ValiditeFonctionnement")
                        .HasColumnType("bit");

                    b.Property<bool>("ValiditeNbrPiece")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RespServiceQualiteId");

                    b.ToTable("RapportTestQualite");
                });

            modelBuilder.Entity("GAP.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tutulaire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GAP.Models.ReceptServiceAchat", b =>
                {
                    b.HasBaseType("GAP.Models.User");

                    b.HasDiscriminator().HasValue("ReceptServiceAchat");
                });

            modelBuilder.Entity("GAP.Models.RespServiceAchat", b =>
                {
                    b.HasBaseType("GAP.Models.User");

                    b.HasDiscriminator().HasValue("RespServiceAchat");
                });

            modelBuilder.Entity("GAP.Models.RespServiceFinance", b =>
                {
                    b.HasBaseType("GAP.Models.User");

                    b.HasDiscriminator().HasValue("RespServiceFinance");
                });

            modelBuilder.Entity("GAP.Models.RespServiceQualite", b =>
                {
                    b.HasBaseType("GAP.Models.User");

                    b.HasDiscriminator().HasValue("RespServiceQualite");
                });

            modelBuilder.Entity("GAP.Models.DemandeAchat", b =>
                {
                    b.HasOne("GAP.Models.RespServiceAchat", null)
                        .WithMany("DemandesAchats")
                        .HasForeignKey("RespServiceAchatUserID");
                });

            modelBuilder.Entity("GAP.Models.Devis", b =>
                {
                    b.HasOne("GAP.Models.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GAP.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GAP.Models.RespServiceAchat", null)
                        .WithMany("Devis")
                        .HasForeignKey("RespServiceAchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GAP.Models.Facture", b =>
                {
                    b.HasOne("GAP.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GAP.Models.RespServiceFinance", null)
                        .WithMany("HistoriqueFactures")
                        .HasForeignKey("RespServiceFinanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GAP.Models.OffreVente", b =>
                {
                    b.HasOne("GAP.Models.Fournisseur", "Provider")
                        .WithMany("OffreVente")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("GAP.Models.Produit", b =>
                {
                    b.HasOne("GAP.Models.OffreVente", null)
                        .WithMany("Produit")
                        .HasForeignKey("OffreVenteId");
                });

            modelBuilder.Entity("GAP.Models.RapportReception", b =>
                {
                    b.HasOne("GAP.Models.ReceptServiceAchat", null)
                        .WithMany("HistoriqueRapportsReceptions")
                        .HasForeignKey("ReceptServiceAchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GAP.Models.RapportTestQualite", b =>
                {
                    b.HasOne("GAP.Models.RespServiceQualite", "RespServiceQualite")
                        .WithMany("HistoriqueRapportQualite")
                        .HasForeignKey("RespServiceQualiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RespServiceQualite");
                });

            modelBuilder.Entity("GAP.Models.Fournisseur", b =>
                {
                    b.Navigation("OffreVente");
                });

            modelBuilder.Entity("GAP.Models.OffreVente", b =>
                {
                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GAP.Models.ReceptServiceAchat", b =>
                {
                    b.Navigation("HistoriqueRapportsReceptions");
                });

            modelBuilder.Entity("GAP.Models.RespServiceAchat", b =>
                {
                    b.Navigation("DemandesAchats");

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("GAP.Models.RespServiceFinance", b =>
                {
                    b.Navigation("HistoriqueFactures");
                });

            modelBuilder.Entity("GAP.Models.RespServiceQualite", b =>
                {
                    b.Navigation("HistoriqueRapportQualite");
                });
#pragma warning restore 612, 618
        }
    }
}
